# マージするPRにつけるラベルの条件
labels:
  - auto_merge
  - dependencies

merge_type: squash    # マージモード (optional): merge, squash, rebase デフォルト: merge
delete_branch: delete # マージ後にブランチを削除するかどうか (optional): delete または 空欄