# This is a basic workflow to help you get started with Actions

name: CI_Product

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  release:
    types:
      - created

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      #- uses: actions/checkout@v2

      # Deploy to staging environment
      - name: Deploy
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_ADDR: ${{ secrets.SSH_ADDR }}
          SSH_PORT: ${{ secrets.SSH_PORT }}
          SSH_COMMAND: ${{ secrets.SSH_COMMAND_PROD }}
        run: |
          echo "$SECRET_KEY" > secret_key
          chmod 600 secret_key
          ssh -oStrictHostKeyChecking=no ${SSH_USER}@${SSH_ADDR} -i secret_key -p ${SSH_PORT} "$SSH_COMMAND"
